enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  f2480787-c9ba-4dca-ab9f-c3bf979635f5:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
